# .streamlit/secrets.toml
[ods_api]
token_url = "https://doe-edfiods-a-c-v2026-ca.grayisland-7cb4ec7b.eastus.azurecontainerapps.io/2026/oauth/token"
api_key = "130-144-1017300000"
api_secret = "b1b99eb7c5f345cd8f83763f0faa61ce"